### ISSUE TITLE
Rounding error

### ISSUE THREAD

**Issue by philippetrepanier** [scurker/currency.js#102]
When multiplying two numbers with different precision the rounded value is not the right one in the following case : `XX.X55` with precision 2. The value returned is `XX.X5` instead of `XX.X6`.

Here is an example:
```
var taxVal = currency(0.09975, {precision: 5}) 
// {intValue: 9975, value: 0.09975, s: {…}, p: 100000}

var amount = currency(180)
// {intValue: 18000, value: 180, s: {…}, p: 100}


amount.multiply(taxVal)
// {intValue: 1795, value: 17.95, s: {…}, p: 100}
```
The expected value would be `1796` with Banker's Rounding.

Is this the expected rounding behavior?

**Comment by scurker** [comment]
Currency doesn't implement banker's rounding and should always be half up. It looks like you may have found an edge case as `currency(17.955)` also produces the same issue.
