### ISSUE TITLE
Rounding bugs

### ISSUE THREAD

**Issue by pdcmoreira** [scurker/currency.js#116]
Test: `currency('1312.444445', {precision: 2})`
Expected: `1312.45`
Got: `1312.44`

Test: `currency(1312.45, {precision: 0})`
Expected: `1313`
Got: `1313`

Test: `currency('1312.45', {precision: 0})`
Expected: `1313`
Got: `1312`

Only the second test yields a correct result! Then if I just pass the value as string instead of a number, the result is wrong!

**Comment by scurker** [comment]
Looks like I handled numeric rounding in #102, but completely missed string rounding. Good catch! I'll have a patch release soon.

**Comment by pdcmoreira** [comment]
Cool, but shouldn't `1312.444445` with precision 2 round to `1312.45`?

**Comment by fanckush** [comment]
@scurker this bug is still present for example
``` js
currency(99.49, {precision: 0}).value        // --> returns 99 instead of 100
```

in fact, the 1st and 3rd test cases from the issue fail as well (both in string and number formats)

am I doing something wrong?

**Comment by scurker** [comment]
> [@scurker](https://github.com/scurker) this bug is still present for example
> 
> currency(99.49, {precision: 0}).value        // --> returns 99 instead of 100
> in fact, all 3 cases from the issue fail now somehow
> 
> am I doing something wrong, or did something change in the lib since then?

Just curious, how is that a rounding bug? currency.js [rounds half up](https://en.wikipedia.org/wiki/Rounding#Rounding_half_up), so any value below half will round down. Since the precision is 0 and the decimal value (`.49`) is less than half, it rounds half down.

**Comment by fanckush** [comment]
@scurker you are correct, it's not a bug. My understanding was incorrect of the rounding

**Comment by pdcmoreira** [comment]
My initial interpretation of the rounding behavior was wrong aswell, because of the discrepancy between the second and third case (that got fixed in the meantime).
