### ISSUE TITLE
Add explanation of .value property to README.md

### ISSUE THREAD

**Issue by miltonhowe** [scurker/currency.js#120]
It would be useful if you included an explanation of the `.value` and `.intValue` properties on the home README.md page. The `.value` property is an important one as it makes your library able to seamlessly replace js floating point arithmetic, using two js `number`s to produce another js `number` without the bugs of IEEE754

**Comment by scurker** [comment]
`.value` and `.intValue` are mentioned in the docs under usage [/docs/01-usage.md](https://github.com/scurker/currency.js/blob/master/docs/01-usage.md). Do you have any suggestions on how I can make this more clear?
