### ISSUE TITLE
Rounding precision

### ISSUE THREAD

**Issue by tvainika** [scurker/currency.js#133]
I modified your unit test *should default rounding when parsing* to use `var round1 = currency(1.2349)` instead of current `1.234` and that caused rouding to break (not half-up).

**Comment by scurker** [comment]
Currently, the bulk of the rounding happens inside of `parse` and relies on `Number.toFixed()` for decimal rounding.

https://github.com/scurker/currency.js/blob/2eaefbee7fe49081b6e3a8d3fa02fa2533edc4ee/src/currency.js#L76-L77

Part of the issue at the moment, is only half cents are taken into consideration in this calculation. So `1.2349` will get parsed internally as `123.4` which eventually rounds down to `123`. Accounting for more decimals could potentially lead to a precision loss on higher numbers, but I need to do some testing around this to verify.

**Comment by charlie-s** [comment]
1.2349 appears to be getting parsed internally as 123.49, and then rounded to 124, due to `Number(123.49).toFixed(1)` rounding .49 to .5, and then the final `round` call turning 123.5 into 124.

Is there harm in using `.toFixed(2)`?

**Comment by scurker** [comment]
It's more of an issue of agnostically handling _any_ arbitrary precision. Using `.toFixed(2)` will solve a greater amount of cases, but it feels like it's not truly addressing the issue. It's definitely something that can make the next release, but I want to ensure there's a better scalable solution long term.

**Comment by scurker** [comment]
Fortunately, `toFixed(x)` does not exhibit the same floating point issues since it's a string so even `toString(100)` would work, so it's possible it could be an option. But mostly I haven't been able to center on a good solution yet that resolves a ton of edge cases without bloating the library a whole bunch.

**Comment by popod** [comment]
What about this to round without errors ?

```
let roundedPrice = +(Math.round(price + 'e2') + 'e-2')
```

see: https://stackoverflow.com/a/19722641/8697449

**Comment by scurker** [comment]
I bumped up the internal precision slightly to account for errors. Should handle a greater number of cases within reasonable values.
