### ISSUE TITLE
Rounding error with precision

### ISSUE THREAD

**Issue by popod** [scurker/currency.js#138]
Hi,

It seems that rounding with option `precision` does not works correctly in some case:

- `currency(0.43499, { precision: 2 }) => 0.44`, but `0.43` is expected
- `currency(1.354999, { precision: 2 }) => 1.36`, but `1.35` is expected

**Comment by scurker** [comment]
This is related to #133, follow that for comments.

**Comment by popod** [comment]
Ok, thanks !
