### ISSUE TITLE
Format bug

### ISSUE THREAD

**Issue by darlinglele** [scurker/currency.js#139]
let CHY = value => currency(value, {precision: 2})
let result = CHY(99999747361065.39).format()
expected : 99,999,747,361,065.39 
actual: 99,999,747,361,065.41

**Comment by scurker** [comment]
Thanks for the issue! Unfortunately, this isn't a bug but expected behavior.

> As long as your currency values are less than 2<sup>53</sup> (in cents) or 90,071,992,547,409.91 you should be okay.

Since currency values are stored internally as integers, any number larger than the above will result in precision loss.

**Comment by darlinglele** [comment]
Thank a lot for the reply
