### ISSUE TITLE
Allow currency objects to passed as parameters

### ISSUE THREAD

**Issue by rapilabs** [scurker/currency.js#15]
In the arithmetic methods, allow another currency object to be passed, similar to moment.js.

Current solution is to `currObj.add(anotherCurrObj.value)`

**Comment by scurker** [comment]
@rapilabs You can add two currency values together, it's just currently undocumented.

```javascript
var a = currency(0.01);
var b = currency(0.02);
a.add(b); // "0.03"
```

I plan on doing another release fairly soon, so I'll update the documentation to include this.

**Comment by scurker** [comment]
Should now be fully documented.
