### ISSUE TITLE
Feature: add abbreviation support

### ISSUE THREAD

**Issue by mrmarktyy** [scurker/currency.js#164]
Great lib 👍 
It would be even better if supporting abbreviation in future.

For example:
1000 -> 1k
1,000,000 -> 1m
etc

**Comment by scurker** [comment]
This should now be possible with [`v2.0.0`](https://github.com/scurker/currency.js/releases/tag/v2.0.0) where currency can now accept a custom formatter option.

**Comment by scurker** [comment]
At this time, this isn't something I would want to support as part of the core part of the library.
