### ISSUE TITLE
Allow instanciating currency in cents instead of dollars

### ISSUE THREAD

**Issue by natefoundry** [scurker/currency.js#166]
I'd like to be able to create a currency object with a value that is in cents instead of dollars.

Example:

```
const amount = currency(500, { denomination: 'cents' }) // $5.00, not $500.00
```

**Comment by peitalin** [comment]
Can't you just divide by 100?

**Comment by ryanwood** [comment]
This would be useful when dealing with currencies with different precisions. I have currency configuration sent from the server and all money is represented in cents on the front-end. It would be nice to be able to "hydrate" a currency object from the cents & precision:

```js
const amount = currency.fromCents(500, { precision: 2, symbol: '$' }) // $5.00
const amount = currency.fromCents(500, { precision: 0, symbol: '¥' }) // ¥500
const amount = currency.fromCents(500, { precision: 3, symbol: 'BD' }) // BD0.500
```

**Comment by scurker** [comment]
[`v2.0.0`](https://github.com/scurker/currency.js/releases/tag/v2.0.0) has just been released allowing you to optionally parse the initial value as cents.
