### ISSUE TITLE
internet explorer doesn't work

### ISSUE THREAD

**Issue by xaniotis27** [scurker/currency.js#178]
Hello and thank ypu for this library..
I noticed that in Internet explorer doesn't work,

I user the below code:
var euro = value => currency(value, { separator: '.', decimal: ',', precision : decimalCount });
abd in console of Internet Explorer says: "Syntax error"

**Comment by scurker** [comment]
If you're not using a compiler like [babel](https://babeljs.io/) or [typescript](https://www.typescriptlang.org/), you won't be able to use arrow functions.

The non-arrow function version would look like this:

```
var decimalCount = 2;
var euro = function(value) { 
  return currency(value, { separator: '.', decimal: ',', precision : decimalCount });
}
```
