### ISSUE TITLE
Format dollars only when cents are 0

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [scurker/currency.js#191]
Suppose I have precision=2 in dollars. However when the value is whole dollars, it is overwhelming for the user to see `$50.00`, instead of just `$50`. 
I propose adding yet another config option to indicate whether `currency.js` should do such formatting. For example: `{ omitZeroCents: true }`.

If this proposal sounds well, I am willing to make a PR.
Thanks

**Comment by abdullahsari** [comment]
I'm pro since it's also usual to replace the 00 with - in the Benelux, e.g. € 78,-

**Comment by Dragomir-Ivanov** [comment]
@scurker Any advice on this issue?

**Comment by scurker** [comment]
@Dragomir-Ivanov At the moment I don't have any specific advice. I'm starting to plan `2.0.0` things and one of the things I'd like to tackle is custom formatting and better i18n handling. Ideally formatting would be a function that would give you complete flexibility and possibly even hook into `Intl.NumberFormat`.

**Comment by Dragomir-Ivanov** [comment]
Thanks @scurker , that is so cool. But what about current 1.x? I do think this small extension will not harm.

**Comment by scurker** [comment]
No ETA on this release as it's still being worked on, but this will be possible as part of the `2.0.0` release. 

`format` can then be a function, allowing you to customize its output.

_Example:_

```js
function format(currency, options) {
  // call original format function to get its string value
  let format = options.format(currency, options);

  if(currency.cents() === 0) {
    // trim decimal and any trailing zeros
    return format.slice(0, format.length - (options.precision + 1));
  }

  return format;
}

currency(1.00).format(format); // => "$1"
currency(1.23).format(format); // => "$1.23"
```

**Comment by Dragomir-Ivanov** [comment]
I have patched it, privately. It seems to work just fine:
```
  format(useSymbol) {
    let { pattern, negativePattern, formatWithSymbol, symbol, separator, decimal, groups, replaceZeroCents } = this._settings
      , values = (this + '').replace(/^-/, '').split('.')
      , dollars = values[0]
      , cents = values[1];

    if (replaceZeroCents !== undefined) {
      function rtrim(str) {
        return str.replace(/0*$/, '');
      }
      cents = rtrim(cents)
    }

    // set symbol formatting
    typeof (useSymbol) === 'undefined' && (useSymbol = formatWithSymbol);

    return (this.value >= 0 ? pattern : negativePattern)
      .replace('!', useSymbol ? symbol : '')
      .replace('#', `${dollars.replace(groups, '$1' + separator)}${cents ? decimal + cents : replaceZeroCents || ''}`);
  },
```

**Comment by scurker** [comment]
[`v2.0.0`](https://github.com/scurker/currency.js/releases/tag/v2.0.0) has just been released where the formatter can now be a function allowing you to customize the output formatting (see https://github.com/scurker/currency.js/issues/191#issuecomment-529201820) for example

**Comment by Dragomir-Ivanov** [comment]
Thanks a lot! Will look it up, and probably migrate. Kudos for the good work.

**Comment by ZiedChekir** [comment]
Thank you alot for this feature. I just want to add that the above format function works for the Dollar and the Euro but it does not work for all currencies like the TND where the symbol is at the end example "10.000 TND". So I made this format function that should work fine with all currencies.

```js
function format(currency, options) {
  let format = options.format(currency, options);

  if (currency.cents() === 0) {
    const decimalIndex = format.indexOf(options.decimal);
    if (decimalIndex !== -1) {
      format =
        format.slice(0, decimalIndex) +
        format.slice(decimalIndex + options.precision + 1);
    }
  }

  return format;
}
```
