### ISSUE TITLE
Object.assign not working in IE11-

### ISSUE THREAD

**Issue by TheUser444** [scurker/currency.js#193]
a=Object.assign({},m,a); in version 1.2.1 is not working in IE11 and below.

**Comment by scurker** [comment]
At the moment, this is intended. `currency.js` currently targets [evergreen browsers and >1%](https://github.com/scurker/currency.js/blob/master/.browserslistrc). Including a polyfill as part of the library would likely increase the size of `currency.js` by 20-30%.

My recommendation is to either:

A) Ensure that `currency.js` runs through [babel targeting IE11 in its browser list](https://babeljs.io/docs/en/babel-preset-env).

_or_

B) Include an `Object.assign` polyfill like [es6-object-assign](https://www.npmjs.com/package/es6-object-assign).
