### ISSUE TITLE
dollars function on big numbers

### ISSUE THREAD

**Issue by Mowafy** [scurker/currency.js#226]
currency('90071992547').dollars(); 
expected: 90071992547
actual: -122320669

tested on Firefox 71 & Chrome 78

**Comment by scurker** [comment]
This is a [[known limitation due to integer limits](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)

**Comment by Mowafy** [comment]
I think the problem in the double telda in the dollar method
` let tmp = 90071992547.1234;
console.log(~~tmp); 
// expected: 90071992547, actual: -122320669

console.log( Math.floor(tmp) ); 
// expected: 90071992547, actual: 90071992547
`
