### ISSUE TITLE
Decimal formatting error when formatting to new symbol

### ISSUE THREAD

**Issue by rtman** [scurker/currency.js#236]
Hi,

I've encountered this situation where if you input a string into currencyJs and you are trying to swap out the decimal and grouping symbols, it will incorrectly do so. If you input a number it will do it correctly.

Here is my settings:

```
currencyJs(value, {
    decimal: ",",
    separator: ".",
    precision: 2
  });
```

If I input "1.00" I get "100,00" - incorrect
If I input 1.00 I get "1,00" - correct

[Here is a demo of the issue](https://codesandbox.io/s/inspiring-greider-eio97)

Is this a bug or am I using it incorrectly?

**Comment by scurker** [comment]
It's parsing the decimal value `.` as a separator when used with the options `{ decimal: ',', separator: '.' })` so the string `"1.00"` formatting as `"100,00"` is correct here.

A better example of this would be to input `1.000,00` as a string value which will format as `"1.000,00"` and return a numeric value of `1000.00`. currency attempts to parse and format string values the same as the options that are initially passed in.

There's no way to currently have a different format option in `1.x`, but this will change in the next major release which can be installed with `npm install currency.js@next`.

With that, you could have different parse and format options:

```js
currency("1000.23").format({ separator: '.', decimal: ',' }); // => "1.000,00"
```

**Comment by scurker** [comment]
The alternative for the current version would be to use 2 different currency objects to parse and format:

```js
var format = value => {
  var parsedValue = currency(value);
  return currency(parsedValue, { separator: '.', decimal: ',' });
};
```

**Comment by rtman** [comment]
@scurker thanks for the explanation! I'll try and make this work with those examples
