### ISSUE TITLE
Ability to extract and re-use the currency format

### ISSUE THREAD

**Issue by denisk20** [scurker/currency.js#242]
Is it possible to extract the format from a string value, manipulate it and format it back? For example

`currency('10 €').add(1).format() === '11 €'`

**Comment by scurker** [comment]
Yup! There's even a test that demonstrates that:

https://github.com/scurker/currency.js/blob/92e704d3e3642e4287cba5a8ebda1aa3cf2086d8/test/test.js#L237-L243

**Comment by denisk20** [comment]
The following test fails though
```
  const c1 = currency('1 $')
  const c2 = currency ('$ 1')

  expect(c1.add(c2).format()).toEqual('2 $')
  expect(c2.add(c1).format()).toEqual('$ 2')
```

**Comment by scurker** [comment]
You're missing the formatter options for the currency objects:

```js
const c1 = currency('1 $', { pattern: '# !', formatWithSymbol: true, precision: 0 })
const c2 = currency('$ 1', { pattern: '! #', formatWithSymbol: true, precision: 0 })

c1.add(c2).format() // => "2 $"
c2.add(c1).format() // => "$ 2"
```

This will change slightly in the next version, formatters can be set a the top level, or in the format function itself:

```js
var c1 = currency(1.23, { ...formatOptions })
c1.format({ ...formatOptions })
```

It doesn't infer the format from the string value, but is an implicit setting.

**Comment by denisk20** [comment]
My intention was to infer the format from string value. Do you think it's feasible / reasonable to add this option? Should be doable. Let me know if you're interested in a PR.

**Comment by scurker** [comment]
It's possible, but it would be a breaking change from the existing implementation. It would also need to how to parse tokens as `"1,000.00"` and `"1.000,00"` are both valid currencies in different locales. What is your use case where you would like the format to be inferred from the string value?
