### ISSUE TITLE
The "precision" option handles both precision for storage and for formatting

### ISSUE THREAD

**Issue by marknorrapscm** [scurker/currency.js#254]
Ideally we would have an option for precision that is used for calculations and a separate option for formatting. For example, you may want a precision of 4, but then want to display only 2 decimal places. Here's an example:

**The math:**

> 0.555 * 3 = 1.665

**And in code:**

`currency("0.555", { precision: 4 }).multiply(3).format()`
> This outputs 1.6650 as expected

`currency("0.555", { precision: 2 }).multiply(3).format()`
> This outputs 1.68

The second output of `1.68` is correct when calculating with a precision of 2 but is otherwise mathematically false. There is no option (that I can see) to retain the precision of 4 under the hood and then have the library produce a rounded string value by calling `.format()` (the correct rounded value in this case being `1.67`).

Of course, you could parse it yourself and do the rounding, but this is added work that the library could handle. 

I haven't been using this package for long so apologies if this has been covered elsewhere (or if I'm just plain wrong); I checked the closed issues and didn't see this mentioned. Is it possible to achieve what I want using the existing currency.js?

**Comment by scurker** [comment]
This is now possible in `v2` with [custom formatters](https://currency.js.org/#format-default-null).

```js
import currency from 'currency.js'

const format = c => c.value.toFixed(2)
const c1 = value => currency(value, { precision: 3, format })

c1(1.234).value // 1.234
c1(1.234).format() // => "1.23"
```
