### ISSUE TITLE
`fromCents` does not play nicely with `multiply`

### ISSUE THREAD

**Issue by chrisvariety** [scurker/currency.js#260]
Love the new ✨ 2.0 release. Unfortunately I'm running into an issue using it in conjunction with `multiply`, for example:

`currency(300, {fromCents: true}).multiply(2).intValue`

I would expect `600` as the output here, but it is actually `6`. 

I can confirm the `intValue` of `currency(300, {fromCents: true}).intValue` is 300 as expected, so it seems like the precision is getting lost along the way of multiplication.

Weirdly, this does not reproduce with `currency(300, {fromCents: true}).divide(2).intValue`, so it seems specific to `multiply` to me.

CC @ryanwood

**Comment by chrisvariety** [comment]
It looks like `currency(300, {fromCents: true}).add(currency(200, {fromCents: true})).intValue` doesn't work either, producing the output `3`, so this may be more systemic than just `multiply` unfortunately.

**Comment by scurker** [comment]
It's because the arithmetic methods are attempting to calculate precision based on the value into a new currency object when `fromCents` is set to true.

This seems like a pretty critical issue as `fromCents` implementation is broken, but I don't know enough how people are using it.

Do these assertions match what should be expected?

```js
// Basic arithmetic methods should match the source `fromCents` settings
currency(123, { fromCents: true }).add(1).intValue === 124 // true
currency(123, { fromCents: true }).subtract(1).intValue === 122 // true

// Multiple/divide and other methods should use absolute values
currency(123, { fromCents: true }).multiply(2).intValue === 246 // true
currency(123, { fromCents: true }).divide(2).intValue === 62 // true
currency(123, { fromCents: true }).distribute(2) === [62, 61] // true
```

I would think the `add` and `subtract` methods should also deal in cents with their respective params.

**Comment by chrisvariety** [comment]
@scurker yes, that looks good to me, agreed `fromCents` appears pretty critically broken at a glance, I've downgraded to `1.x` for now.

**Comment by scurker** [comment]
I'd like to get a patch release ASAP since this is breaking expected functionality as soon as I can put away some time to dig into it unless someone else comes up with a fix first.

**Comment by scurker** [comment]
@chrisvariety A fix for this was just released on the `next` tag.

`npm install currency.js@next`

Would you like to verify that everything works correctly?

**Comment by scurker** [comment]
Just released fixes for this, so you should be able to update to `latest`.

**Comment by chrisvariety** [comment]
@scurker these changes look and work great for me, thanks so much! 🙏
