### ISSUE TITLE
Support for Peso (₱) symbol

### ISSUE THREAD

**Issue by edrichhans** [scurker/currency.js#274]
Hello, will there be support for the peso ₱ symbol? It formats to ±.

`return currency(value, { symbol: "₱", separator: ",", decimal: "." }).format()`

Thanks.

**Comment by scurker** [comment]
Can you provide any additional information? I just tested this in my console:

```
currency(1.00, { symbol: "₱", separator: ",", decimal: "." }).format()
> "₱1.00"
```

**Comment by edrichhans** [comment]
If that's the case then it might be a problem with my PDF generating library. The value with the currency symbol is being passed onto [PDFKit](https://pdfkit.org/) to generate documents in PDF format.

**Comment by scurker** [comment]
I would check what font you're using within PDFKit to see what support there is for that symbol.
