### ISSUE TITLE
How to use negative precision in currency.js?

### ISSUE THREAD

**Issue by sayonnara** [scurker/currency.js#294]
**Is there a negative precision in currency.js?**
Cambodia currency (name: Riel (រៀល), code:KHR symbol:៛) smallest note is 50riel but we always use 100riel for the smallest. 

**Expected**
currency(1234.56, {symbol:'៛', precision:-2, pattern:'# !'}).format(); // 1200 ៛
currency(1250.56, {symbol:'៛', precision:-2, pattern:'# !'}).format(); // 1300 ៛

**Actual Result**
Currently when I use precision -2 I got pretty print message in console log as below.
Uncaught RangeError: toFixed() digits argument must be between 0 and 100

**Comment by scurker** [comment]
You may want to try [`increment`](https://currency.js.org/#increment-default-null):

> When implementing a currency that implements rounding, setting the increment value will allow you to set the closest increment to round the display value to.

```js
currency(1234.56, { 
  symbol: '៛', 
  precision: 0, 
  pattern: '# !', 
  increment: 100 
}).format() // 1,200 ៛
```

The internal value will still keep the same number (`1234.56`) and will only use the increment value on `.format()`.

**Comment by sayonnara** [comment]
Thank @scurker
