### ISSUE TITLE
Invalid formatting for negative numbers

### ISSUE THREAD

**Issue by Koldunz** [scurker/currency.js#295]
```
const currency = require("currency.js");
const value = -100000;
console.log(currency(parseFloat(value)).format(true););
```

Version: 2.0.3
Expected Result: $-100,000.00
Actual result: -$100,000.00

**Comment by scurker** [comment]
This is the default negative pattern, you can customize this with options:

```js
currency(-100000).format({ negativePattern: '!-#' }) // $-100,000.00
```

**Comment by Koldunz** [comment]
> This is the default negative pattern, you can customize this with options:
> 
> ```js
> currency(-100000).format({ negativePattern: '!-#' }) // $-100,000.00
> ```

Thanks. Already found this setting and closed the issue
