### ISSUE TITLE
Add Symbol to the end?

### ISSUE THREAD

**Issue by ivanjeremic** [scurker/currency.js#342]
In Europe, it is very common to have the `€` Symbol at the end like `1,000 €` but I can't find how to do this with currency.js is there any way? If I would like to suggest this feature.

**Comment by scurker** [comment]
Take a look at [`pattern`](https://currency.js.org/#pattern-default-):

```
currency(1.23, {
  pattern: `# !`
}).format(); // => "1.23 $"
```
