### ISSUE TITLE
Add valueOf() method for returning numeric value

### ISSUE THREAD

**Issue by tmorehouse** [scurker/currency.js#35]
Consider adding a `valueOf()` method, to complement the current `toString()` method, which would return the numeric value of the currency.

Currently when comparing two currencies, they compare alphabetically (because `toString()` is used):
```js
currency(20.00) > currency(10000) === true
```
When in fact they should be compared numerically (and the above would be `=== false`).

Adding `.valueOf()` (which would just return `.value`) would allow for such situation.

**Comment by tmorehouse** [comment]
As a side note...

For "safety", I think  `.value` should be changed to a getter (and have no setter) that computes the value on the fly.  That way someone doesn't try and set value and expect it to still work, although having a setting could be handy too.

```js
Object.defineProperty(currency, 'value', { 
  get: function() {
    return that.intValue / this.precision;
  },
  set: function(v) {
    this.intValue = parse(v, this.settings);
  }
});
```

And documenting that the `.value` property exists so that people know it is available to get the numeric value for comparisons( `<`, `>`, etc).

**Comment by scurker** [comment]
A significant issue with `Object.defineProperty` is its speed. [Running benchmarks](https://jsperf.com/currency-js-parse-tests) for `this.value` vs. `Object.defineProperty` show that it is significantly slower. 

![image](https://user-images.githubusercontent.com/1062039/28681042-b51de04c-72bd-11e7-9858-d090b75e22aa.png)

This test case is pretty simple, but for our use case we're working with thousands of values with different multiplications so a 70% hit to performance could be pretty significant.

If a value needs to be _readonly_, Typescript or Flow might be better options to provide compile time hints as opposed to runtime.

**Comment by tmorehouse** [comment]
What about for `get` speeds?   I see get being more useful that set.(usually, for this type of thing)

**Comment by scurker** [comment]
The benchmark is for only using `get` speeds. Essentially the two versions are:

```javascript
this.value = v / precision;
this.intValue = v;
```
### vs.

```javascript
Object.defineProperties(this, {
  value: { get: () => v / precision },
  intValue: { get: () => v }
});
```

**Comment by tmorehouse** [comment]
I was just thinking more on the line of `.value`, which would be useful as a public read only value, for comparisons of value (i.e. `<`, `>`, etc), and when the user wants a the value of the currency as a numeric value and not a fixed precision string or formatted value.

`intValue` could remain as is.

**Comment by scurker** [comment]
I did some pretty extensive testing around adding `.valueOf()`.

The major issue being is that `.valueOf()` nearly always takes priority over `.toString()`. This can cause conflicts with React, Angular, Server-Side Templating, etc. because the primitive `.valueOf()` will be used instead of `.toString()` causing `currency(1.00)` to be displayed as `1`. Generally when dealing with currencies, the default should most likely to be include the full decimal values for display.

Unfortunately this means for comparisons, `.value` will need to be used for value comparisons.

**Comment by tmorehouse** [comment]
Which would be  good reason to make `.value` a getter property (to prevent accidental overwrite), and provide a bit of documentation mentioning `.value` as the numeric value available for numeric comparisons.

**Comment by scurker** [comment]
While I agree using `Object.defineProperty(...)` would be nice, I don't think it's worth the performance hit to implement. However, I do think it's worth having static typing to help with this, so I've opened #36 and #37 to add Typescript and Flow definitions respectively.

**Comment by scurker** [comment]
@tmorehouse I thought about this more, and wanted to experiment with a babel plugin. You may want to check out [babel-plugin-transform-currency-operators](https://github.com/scurker/babel-plugin-transform-currency-operators). It allows for more natural usage of currency, and would love to have your input!

**Comment by tmorehouse** [comment]
Cool, I'll check it out for sure.
