### ISSUE TITLE
Scientific notation support

### ISSUE THREAD

**Issue by ghtaylor** [scurker/currency.js#412]
# Expected Behavior

1. Provide a string `value` that uses scientific notation to `currency(value)` 
2. Value represented in `currency` object is **correct**

# Actual Behavior

1. Provide a string `value` that uses scientific notation to `currency(value)` 
2. Value represented in `currency` object is **incorrect**

# Steps to Reproduce the Problem

[*CodeSandbox describing problem*](https://codesandbox.io/s/currency-js-scientific-notation-issue-t8snsu)

1. Declare string that is a currency amount represented by scientific notation:
```typescript
const scientificNotationAmount: string = "1.299078055E7";
```

2. Provide string as `value` to `currency(value)`
```typescript
const amount = currency(scientificNotationAmount);
```

3. Log `.value` property of `amount`
```typescript
// Currency.js value
console.log(amount.value) // 1.3
// Expected value
console.log(Number(scientificNotationAmount)) // 12_990_780.55
```

# Motivation
Whilst integrating with a third-party accounting and finance management system, their APIs return amount values over 10,000,000 or less than -10,000,000 as scientific notation values. We did not know that `currency.js` doesn't pick this up, and it caused a bug in our system.

# Note
I am happy to try and make a PR if its agreed this would be a worthwhile enhancement? Please let me know.

**Comment by scurker** [comment]
I'm not sure how common this is, having currency values formatted as scientific notation isn't something that I've commonly seen. Ideally currency.js is intended to be a lightweight currency formatter with a lot of bloat, so I'm not inclined to include a feature that's not commonly used.

My short suggestion would be if you know a value is in scientific notation, is to throw the value into `Number` and let currency do the rest. It should be safe for numeric values as well:

```js
currency(Number('1.299078055E7'))
```
