### ISSUE TITLE
Fails to parse and format values < 1.e-6

### ISSUE THREAD

**Issue by clemens-msupply** [scurker/currency.js#470]
I get the following results here:

```ts
const t1 = currency(0.000001, { precision: 10 }).format(); // "$0.000001"
const t2 = currency(0.0000001, { precision: 10 }).format(); // "$0.-7"
```
I guess currency() tries to parse the js number converted to a string ("1e-7") which fails?

**Comment by scurker** [comment]
I'm unable to reproduce this, what environment is this happening in?

**Comment by clemens-msupply** [comment]
You are right, I missed that we are using a custom formatter... Sorry for that.
