### ISSUE TITLE
Option to do rounding

### ISSUE THREAD

**Issue by danielgrana** [scurker/currency.js#70]
Some currencies in common usage need some rounding. E.g. CHF when used for billing needs to be rounded to the next 0.05 value
* 1.342 => 1.35
* 1.3216 => 1.30

Add option to format or additional method .round to library

**Comment by scurker** [comment]
Hi @danielgrana, I'm considering this, but I need a better understanding of the different scenarios for rounding. I know as a lot of countries have moved away from `.01` values that rounding has become more common.

Most likely rounding would happen at the end, `currency(1.342).add(.001) => 1.35` but I need to consider different decimal values along with different rounding modes (half up, half down, etc.)

**Comment by scurker** [comment]
I've worked this into 1bcb151 with the idea that rounding should only happen on display, so when currency is resolved as a string or using `format()`. Internal values are unchanged. You can try this out before it gets released with `npm install currency.js@next`.

Documentation still needs to be updated, but to round to the nearest `.05`, you can set `increment` as an option:

```javascript
let currencyRounded = value => currency(value, { increment: .05 });

let c1 = currencyRounded(1.01);
let c2 = currencyRounded(0.99);
let c3 = currencyRounded(1.00).add(.04);

c1.format(); // "1.00"
c1.value;    // 1.01

c2.format(); // "1.00"
c2.value;    // .99

c3.format(); // "1.05"
c3.value;    // 1.04
```

**Comment by leejaen** [comment]
+1, I have the same issue, could you please add this feature? @scurker

**Comment by scurker** [comment]
@leejaen Yes! It's slated for `v1.1.0`. I'm still working on documentation for the next version, so it's not released yet, but you can try it out on the next tag via `npm install currency.js@next`.

**Comment by leejaen** [comment]
Thank you!

**Comment by danielgrana** [comment]
👍👍👍
