### ISSUE TITLE
installed v 1.0.2 from npm is empty

### ISSUE THREAD

**Issue by vagusX** [scurker/currency.js#78]
installed from npm and this package is a empty package only include these files
![screen shot 2017-12-29 at 2 56 04 pm](https://user-images.githubusercontent.com/6828924/34431253-87ebc034-eca8-11e7-8b7c-6041ecea0d43.png)

**Comment by scurker** [comment]
Thanks for the heads up @vagusX. I released `v1.0.4` that has the files. It looks like Travis is failing at deploying at the moment.
